### PR TITLE
Search for debugger

### PR DESCRIPTION
**Pull request by andrewc12**
Add more locations the debugger might be in
Signed-off-by: Andrew Innes <andrew.c12@gmail.com>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by andrewc12** [comment]
@EchterAgo any thoughts?

**Comment by EchterAgo** [comment]
Yes, I think we should substitute env vars and use `%ProgramFiles%` / `%ProgramFiles(x86)%`. I'll also check if there is a registry key for the location

**Comment by EchterAgo** [comment]
```
>>> import pathlib
>>> import os           
>>> pf = pathlib.Path(os.environ["ProgramFiles"])
>>> cdb = pf / "Windows Kits" / "10" / "Debuggers" / "x64" / "cdb.exe" 
>>> cdb
WindowsPath('C:/Program Files/Windows Kits/10/Debuggers/x64/cdb.exe')
```

**Comment by EchterAgo** [comment]
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots\KitsRoot10` is probably what we should try first.

**Comment by EchterAgo** [comment]
There is also `WindowsDebuggersRoot10` (`C:\Program Files (x86)\Windows Kits\10\Debuggers\` on my system)

**Comment by EchterAgo** [comment]
```
def read_reg(path: pathlib.Path, hive=winreg.HKEY_LOCAL_MACHINE):
    try:
        with winreg.OpenKey(hive, str(path.parent)) as key:
            value, _ = winreg.QueryValueEx(key, path.name)
            return value
    except (OSError, FileNotFoundError):
        return None


def find_kits():
    kit_value_names = ["KitsRoot10", "KitsRoot81", "KitsRoot"]
    kit_install_path: pathlib.Path = None

    for kit_value_name in kit_value_names:
        kit_reg_path = (
            pathlib.Path("SOFTWARE")
            / "WOW6432Node"
            / "Microsoft"
            / "Windows Kits"
            / "Installed Roots"
            / kit_value_name
        )

        res = read_reg(kit_reg_path)
        if not res:
            continue

        kit_install_path = pathlib.Path(res)
        break

    return kit_install_path
```

**Comment by andrewc12** [comment]
> ```python
> def find_kits():
>     kit_value_names = ["KitsRoot10", "KitsRoot81", "KitsRoot"]
>     kit_install_path: pathlib.Path = None
> 
>     for kit_value_name in kit_value_names:
>         kit_reg_path = (
>             pathlib.Path("SOFTWARE")
>             / "WOW6432Node"
>             / "Microsoft"
>             / "Windows Kits"
>             / "Installed Roots"
>             / kit_value_name
>         )
> 
>         res = read_reg(kit_reg_path)
>         if not res:
>             continue
> 
>         kit_install_path = pathlib.Path(res)
>         break
> 
>     return kit_install_path
> ```

Probably a good idea but I wont be able to recreate the %ProgramFiles%\\Windows Kits\\10\\Debuggers\\x64\\cdb.exe scenario for testing without a clean windows install (I think)

**Comment by andrewc12** [comment]
Thanks for the registry code @EchterAgo

**Pull request merged**
