### PR TITLE
Address ZFS_MODULE_PARAMS using linker_set.h

### PR DESCRIPTION
**Pull request by lundman**
Upstream defines kernel tunables using `ZFS_MODULE_PARAM(...)`, and `ZFS_MODULE_CALL(...)`. The first is just variables of certain type (INT, ULONG), and the second takes a function-pointer to call to parse input.

These variables are often defined `static` and it is undesirable to undo this work, just for the Windows platform. 

To work around this, a `linker_set.h` header file was made, based on the standard Unix `linker set` API. It allows the compiler to add variables defined in different source files, to be collected under a 'named linker set'. This set can then be iterated on, often during initialisation of the program.

Similarly, FreeBSD uses `ZFS_MODULE_PARAM()` to define sysctl structs, and macOS uses `__attribute__(constructor)` to connect the sysctl structs. Windows also creates structs to hold the tunable information, pointer, name, type.

Upon startup, `sysctl_os_init()` will iterate the `ZFS_MODULE_PARAM()` linker-set named `zt_`, and check if each tunable is in Registry. 

A Registry-Change notification callback as added, so that we can refresh the tunables should users change the values in the Registry.

~~This implementation currently ignores the ReadOnly type. (Are there any?)~~
ok no longer ignores them and yes, there are quite a few.

### CODE REVIEW

**Comment by lundman** [comment]
ZFSin_registry

**Comment by lundman** [comment]
Talking with OpenZFS about changing long to uint64_t, since it is impeding this code too.
I wonder if there is a nicer way to set the variable-pointers of $type, but switch will do for now.
I think only setting tunables if Registry value is different is the way to go, currently it sets all each time.
Add code to get notified of Registry changes and update on the fly.

**Comment by lundman** [comment]
Ok, 64 bit work is in there, and populated

next:
* work on ZFS_MODULE_VIRTUAL - which defines call back, and argument parser.
* notify for registry changes.

**Comment by lundman** [comment]
OK Brian indicated that it will probably better to make a new macro for `long` type to use with `ZFS_MODULE_PARAM()` as there are 32bit compiles of ZOL on Linux (and they need to use `long` to match kernel.

Names are hard, but `ZFS_PARAM_LONG` or something.

**Comment by sskras** [comment]
> as there are 32bit compiles of ZOL on Linux

Is this related to 32bit builds for Windows too by a chance?

**Comment by lundman** [comment]
I think I did a 32bit version way back at first, to prove it can, but I didn't think anyone was hankering for a 32bit version? Certainly not much to do to get it to work, but 4GB limit on ram is small, unless it's something embedded?

**Comment by lundman** [comment]
Added the VIRTUAL/CALL back methods, and added STRING type.

next is the notification on changes, so kernel can update.

**Comment by lundman** [comment]
Screen Shot 2022-03-24 at 12 52 13 (2)

**Comment by lundman** [comment]
Some minor quirks, there are a bunch of tunables that are set based on others, so rescanning the values in Registry would set things back to 0.

**Comment by lundman** [comment]
This has been merged.

**Pull request closed without merging**
