### PR TITLE
Update README.md to adjust it to Windows as platform

### PR DESCRIPTION
**Pull request by ShalokShalom**
Since this README has been copied from the original ZFS repo, I change here the mention of Windows to Linux, as "other" operating system.

### CODE REVIEW

**Comment by sskras** [comment]
Not sure what do you mean by saying: **as "other" operating system** .

IMO it would be more correct to leave both Windows and Linux names, as Windows port was definitely being discussed about (at least during the OpenZFS Developer Summit 2021).

**Comment by ShalokShalom** [comment]
This repository contains the code for the Windows implementation. 
Currently, the README says its the repo for Linux and FreeBSD. 
This commit changes this.

**Comment by sskras** [comment]
I agree with the second change. I do not fully with the 1st one (though).

**Comment by ShalokShalom** [comment]
Windows is not a "other" operating system in that context. The text speaks about "other" in the context of "other OS, who use OpenZFS" which is in our case illumos, macOS, Linux and FreeBSD.

**Comment by lundman** [comment]
This PR changes 496 files ?

**Comment by lundman** [comment]
Closing for now, top level readme will change with we merge upstream, and module/os/windows/README.md is used for us right now.

**Pull request closed without merging**
