### PR TITLE
Install after building in workflow

### PR DESCRIPTION
**Pull request by andrewc12**
Signed-off-by: Andrew Innes <andrew.c12@gmail.com>

### Motivation and Context

This tries to install zfs after building it to catch errors that occur on load.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by yurikoles** [comment]
I think it should be _before_ upload.

**Comment by andrewc12** [comment]
I'm doing it after upload because there was a problem a few days ago that crashed the runner.
So the artifacts wouldn't get uploaded.

**Comment by yurikoles** [comment]
My comment is wrong, if install fails, one may want to download the artifact and examine it locally.

**Comment by andrewc12** [comment]
Exactly what I was thinking.

**Pull request merged**
